{
	name: "Deploy static content to Pages",

	# Trigger on push and on manual runs from Actions tab
	on: ["push", "workflow_dispatch"],

	# These permissions allow deployment to GitHub Pages
	permissions: {contents: "read", pages: "write", id-token: "write"},

	# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
	# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
	concurrency: {group: "pages", cancel-in-progress: false},

	jobs: {
		deploy: {
			environment: {
   				name: "github-pages",
	   			url: "${{ steps.deployment.outputs.page_url }}",
	   		},
			runs-on: "ubuntu-latest",
			steps: [
				{uses: "actions/checkout@v4"},
				{uses: "actions/configure-pages@v5"},
				{uses: "actions/upload-pages-artifact@v3", with: {path: "."}},
				{uses: "actions/deploy-pages@v4", id: "deployment"},
			],
		},
	},
}
